// vue3-ts-vite/src/App.vue
<script setup lang="ts"></script>

<template>
  <div class="wrapper">
    <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    <div>vue 3 + vite 4 + typescript 5</div>
  </div>
</template>

<style scoped>
.wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
  padding-top: 100px;
}
.logo {
  height: 32px;
}
</style>

// react-ts-vite/src/App.tsx
import { ReactComponent as ReactLogo } from '@/assets/react.svg';

function App() {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '1rem',
        paddingTop: '100px',
      }}
    >
      <ReactLogo />
      <div>Vite 4 + React 18 + TypeScript 5</div>
    </div>
  );
}

export default App;
